@ApiGateway_HostAddress = http://localhost:5063

GET {{ApiGateway_HostAddress}}/gtw/wallet
Accept: application/json


###
GET {{ApiGateway_HostAddress}}/gtw/ged
Accept: application/json

###
GET {{ApiGateway_HostAddress}}/gtw/ged-compta
Accept: application/json
