
parameters:
- name: environment
  type: string
- name: subscription
  type: string
- name: serviceConnection
  type: string

steps:
- task: AzureCLI@2
  displayName: "Updating config file ocelot.json"
  inputs:
    azureSubscription: ${{ parameters.serviceConnection }}
    scriptType: pscore
    scriptLocation: inlineScript
    inlineScript: |
      Import-Module $Env:PIPELINE_WORKSPACE/Module/Deployment
      Set-EnvironmentVariables -Environment ${{ parameters.environment }} -Subscription ${{ parameters.subscription }}