parameters:
- name: devIndex
  type: number
  default: 0
- name: deployType
  type: string
  default: 'standard'
  values:
    - standard
    - onlyDev
# REC Iteration
- name: recIterations
  type: object
  default:
  - 1
# PRD Iteration
- name: prdIterations
  type: object
  default:
  - 1
# Main branch to apply github flow
- name: githubFlowBranch
  type: string
  default: 'main'

stages:
- stage: build
  displayName: 'Build'
  jobs:
  - job: build
    displayName: 'Build'
    steps:
    - pwsh: Copy-Item -Path $(Build.SourcesDirectory)/src/Config/ocelot.json -Destination $(Build.SourcesDirectory)/pipelines/ocelot.json
    - publish: $(Build.SourcesDirectory)/pipelines
      artifact: Module
- ${{ if ne(parameters.devIndex, 0) }}:
  - stage: DEV
    ${{ if lt(parameters.devIndex, 10) }}:
      displayName: 'Development-dev0${{ parameters.devIndex }}'
      pool: Pulse-dev
    ${{ else }}:
      displayName: 'Development-dev${{ parameters.devIndex }}'
      pool: Pulse-dev
    jobs:
    - deployment: deploy
      displayName: 'Updating config'
      environment: DEV
      strategy:
        runOnce:
          deploy:
            steps:
            - download: current
              artifact: Module
            - template: update-config.yaml
              parameters:
                ${{ if lt(parameters.devIndex, 10) }}:
                  environment: dev0${{ parameters.devIndex }}
                ${{ else }}:
                  environment: dev${{ parameters.devIndex }}
                subscription: ceg-corp-pulse-dev
                serviceConnection: Rydge-dev
- ${{ if and(contains(variables['Build.SourceBranch'], 'develop'), eq(parameters.deployType, 'standard')) }}:
  - stage: ITG01
    displayName: 'Integration'
    pool: Pulse-itg
    jobs:
    - deployment: deploy
      displayName: 'Updating config'
      environment: ITG01
      strategy:
        runOnce:
          deploy:
            steps:
            - download: current
              artifact: Module

            - template: update-config.yaml
              parameters:
                environment: itg01
                subscription: ceg-corp-pulse-itg
                serviceConnection: Rydge-itg
- ${{ if and(and(startsWith(variables['Build.SourceBranch'], 'refs/tags/'), not(contains(variables['Build.SourceBranch'], '-rc.'))), ne(parameters.deployType, 'onlyDev')) }}:
  - ${{ each index in parameters.recIterations }}:
    - stage: REC0${{ index }}
      displayName: Recette-rec0${{ index }}
      pool: Pulse-rec
      ${{ if eq(parameters.devIndex, 0) }}:
        dependsOn: Build
      ${{ else }}:
        dependsOn: DEV
      jobs:
      - deployment: deploy
        displayName: 'Updating REC0${{ index }} config'
        environment: REC0${{ index }}
        variables:
        - name: hubEnvironment
          value: rec0${{ index }}
        strategy:
          runOnce:
            deploy:
              steps:
              - download: current
                artifact: Module

              - template: update-config.yaml
                parameters:
                  environment: $(hubEnvironment)
                  subscription: ceg-corp-pulse-rec
                  serviceConnection: Rydge-rec
  # - stage: PPR1
  #   displayName: Preproduction-J-1
  #   pool: Pulse-ppr
  #   dependsOn:
  #   - REC1
  #   jobs:
  #   - deployment: deploy
  #     displayName: 'Updating J-1 config'
  #     environment: PPR01
  #     variables:
  #     - name: hubEnvironment
  #       value: ppr01
  #     strategy:
  #       runOnce:
  #         deploy:
  #           steps:
  #           - download: current
  #             artifact: Module

  #           - template: update-config.yaml
  #             parameters:
  #               environment: $(hubEnvironment)
  #               subscription: ceg-corp-pulse-ppr
  #               serviceConnection: Rydge-ppr
  - ${{ each index in parameters.prdIterations }}:
    - stage: PRD0${{ index }}
      displayName: Production-prd0${{ index }}
      pool: Pulse-prd
      dependsOn:
      - REC01
      jobs:
      - deployment: deploy
        displayName: 'Updating PRD0${{ index }} config'
        environment: PRD0${{ index }}
        variables:
        - name: hubEnvironment
          value: prd0${{ index }}
        strategy:
          runOnce:
            deploy:
              steps:
              - download: current
                artifact: Module

              - template: update-config.yaml
                parameters:
                  environment: $(hubEnvironment)
                  subscription: ceg-corp-pulse-prd
                  serviceConnection: Rydge-prd
