parameters:
- name: deployToDev
  displayName: 'Déployer sur DEV'
  type: boolean
  default: false
- name: deployToItg
  displayName: 'Déployer sur ITG'
  type: boolean
  default: true
- name: deployToRec
  displayName: 'Déployer sur REC'
  type: boolean
  default: true
- name: deployToPrd
  displayName: 'Déployer sur PROD'
  type: boolean
  default: true
- name: isHotfix
  type: boolean
  default: false
- name: squad
  type: string
  default: none
  values:
    - none
    - transverse
    - tokyo
    - frydge
    - forrest
    - joker

stages:
- ${{ if eq(parameters.deployToDev, true) }}:
  - 'Deployment to DEV environment is no longer supported.': error

- ${{ if and(parameters.deployToPrd, not(parameters.deployToRec), not(parameters.isHotfix)) }}:
  - 'Deploying to REC is mandatory before deploying to PROD.': error

- ${{ if and(not(parameters.deployToItg), not(parameters.deployToRec), not(parameters.deployToPrd)) }}:
  - 'At least one environment must be chosen.': error

- ${{ if and(parameters.isHotfix, not(startsWith(variables['Build.SourceBranch'], 'refs/heads/hotfix/'))) }}:
  - 'Hotfix pipeline must be run from a hotfix/* branch.': error

- ${{ if and(parameters.deployToRec, ne(parameters.squad, 'none')) }}:
  - 'Team configuration cannot be deployed to REC.': error

- stage: build
  displayName: 'Build'
  jobs:
  - job: build
    displayName: 'Build'
    steps:
    - pwsh: Copy-Item -Path $(Build.SourcesDirectory)/src/Config/ocelot.json -Destination $(Build.SourcesDirectory)/pipelines/ocelot.json
    - publish: $(Build.SourcesDirectory)/pipelines
      artifact: Module

# - ${{ if parameters.deployToDev }}:
#   - stage: DEV
#       displayName: 'Development-dev01'
#     pool: Pulse-Linux-dev
#     jobs:
#     - deployment: deploy
#       displayName: 'Updating config'
#       environment: DEV
#       strategy:
#         runOnce:
#           deploy:
#             steps:
#             - download: current
#               artifact: Module
#             - template: update-config.yaml
#               parameters:
#                 environment: dev01
#                 subscription: ceg-corp-pulse-dev
#                 serviceConnection: Rydge-dev

- ${{ if parameters.deployToItg }}:
  - stage: ITG01
    displayName: 'Integration'
    pool: Pulse-Linux-itg
    dependsOn: Build
    jobs:
    - deployment: deploy
      displayName: 'Updating config'
      environment: ITG01
      strategy:
        runOnce:
          deploy:
            steps:
            - download: current
              artifact: Module
            - template: update-config.yaml
              parameters:
                environment: itg01
                subscription: ceg-corp-pulse-itg
                serviceConnection: Rydge-itg
                squad: ${{ parameters.squad }}

- ${{ if or(eq(variables['Build.SourceBranch'], 'refs/heads/main'), startsWith(variables['Build.SourceBranch'], 'refs/tags/'), eq(parameters.isHotfix, true)) }}:
  - ${{ if parameters.deployToRec }}:
    - stage: REC01
      displayName: Recette-rec01
      pool: Pulse-Linux-rec
      dependsOn: Build
      jobs:
      - deployment: deploy
        displayName: 'Updating REC01 config'
        environment: REC01
        strategy:
          runOnce:
            deploy:
              steps:
              - download: current
                artifact: Module

              - template: update-config.yaml
                parameters:
                  environment: rec01
                  subscription: ceg-corp-pulse-rec
                  serviceConnection: Rydge-rec
  # - stage: PPR01
  #   displayName: Preproduction-J-1
  #   pool: Pulse-ppr
  #   dependsOn:
  #   - REC01
  #   jobs:
  #   - deployment: deploy
  #     displayName: 'Updating J-1 config'
  #     environment: PPR01
  #     variables:
  #     - name: hubEnvironment
  #       value: ppr01
  #     strategy:
  #       runOnce:
  #         deploy:
  #           steps:
  #           - download: current
  #             artifact: Module

  #           - template: update-config.yaml
  #             parameters:
  #               environment: $(hubEnvironment)
  #               subscription: ceg-corp-pulse-ppr
  #               serviceConnection: Rydge-ppr
  - ${{ if parameters.deployToPrd }}:
    - stage: PRD01
      displayName: Production-prd01
      pool: Pulse-Linux-prd
      dependsOn:
      - ${{ if parameters.isHotfix }}:
        - Build
      - ${{ else }}:
        - REC01
      jobs:
      - deployment: deploy
        displayName: 'Updating PRD01 config'
        environment: PRD01
        strategy:
          runOnce:
            deploy:
              steps:
              - download: current
                artifact: Module

              - template: update-config.yaml
                parameters:
                  environment: prd01
                  subscription: ceg-corp-pulse-prd
                  serviceConnection: Rydge-prd
