parameters:
- name: devIndex
  type: number
  default: 0
- name: deployType
  type: string
  default: 'standard'
# REC Iteration
- name: iterations
  type: object
  default:
  - 1
  - 2
  - 3

stages:
- stage: build
  displayName: 'Build'
  jobs:
  - job: build
    displayName: 'Build'
    steps:
    - pwsh: Copy-Item -Path $(Build.SourcesDirectory)/src/Config/ocelot.json -Destination $(Build.SourcesDirectory)/pipelines/ocelot.json
    - publish: $(Build.SourcesDirectory)/pipelines
      artifact: Module
- ${{ if ne(parameters.devIndex, 0) }}:
  - stage: deploy_DEV
    ${{ if lt(parameters.devIndex, 10) }}:
      displayName: 'Development-dev0${{ parameters.devIndex }}'
      pool: Pulse-dev0${{ parameters.devIndex }}
    ${{ else }}:
      displayName: 'Development-dev${{ parameters.devIndex }}'
      pool: Pulse-dev${{ parameters.devIndex }}
    jobs:
    - deployment: deploy
      displayName: 'Updating config'
      environment: DEV
      strategy:
        runOnce:
          deploy:
            steps:
            - download: current
              artifact: Module

            - template: update-config.yaml
              parameters:
                ${{ if lt(parameters.devIndex, 10) }}:
                  environment: dev0${{ parameters.devIndex }}
                ${{ else }}:
                  environment: dev${{ parameters.devIndex }}
                subscription: PULSE-DEV
- ${{ if and(contains(variables['Build.SourceBranch'], 'develop'), eq(parameters.deployType, 'standard')) }}:
  - stage: deploy_ITG
    displayName: 'Integration'
    pool: Pulse-itg01
    jobs:
    - deployment: deploy
      displayName: 'Updating config'
      environment: ITG
      strategy:
        runOnce:
          deploy:
            steps:
            - download: current
              artifact: Module

            - template: update-config.yaml
              parameters:
                environment: itg01
                subscription: PULSE-ITG
- ${{ if and(or(contains(variables['Build.SourceBranch'], 'release'), contains(variables['Build.SourceBranch'], 'hotfix')), ne(parameters.deployType, 'onlyDev')) }}:
  - ${{ each index in parameters.iterations }}:
    - stage: deploy_REC0${{ index }}
      displayName: Recettee-rec0${{ index }}
      pool: Pulse-rec0${{ index }}
      ${{ if eq(parameters.devIndex, 0) }}:
        dependsOn: Build
      ${{ else }}:
        dependsOn: deploy_DEV
      jobs:
      - deployment: deploy
        displayName: 'Updating REC0${{ index }} config'
        environment: REC
        variables:
        - name: hubEnvironment
          value: rec0${{ index }}
        strategy:
          runOnce:
            deploy:
              steps:
              - download: current
                artifact: Module

              - template: update-config.yaml
                parameters:
                  environment: $(hubEnvironment)
                  subscription: PULSE-REC
