trigger: none

pool:
  vmImage: 'ubuntu-latest'

resources:
  repositories:
  - repository: Pulse
    name: 'Pulse.Operations.Pipelines'
    type: git
    ref: 'refs/heads/Release/v4.0'

extends:
  template: pipelines/pull-request/back.yaml@Pulse
  parameters:
    name: desktop
    srcPath: src/ApiGateway/ApiGateway.csproj
    testsPath: tests/**/*Tests.csproj
    sonarExclusions: '**/Program.cs, **/Extensions/**,tests/**'