trigger: none

pool:
  vmImage: 'ubuntu-latest'

parameters:
- name: deployToDev
  displayName: 'Déployer sur DEV'
  type: boolean
  default: false
- name: deployToItg
  type: boolean
  displayName: 'Déployer sur ITG'
  default: true
- name: squad
  displayName: 'Squad'
  type: string
  values:
    - transverse
    - tokyo
    - frydge
    - forrest
    - joker

resources:
  repositories:
  - repository: Pulse
    name: 'Pulse.Operations.Pipelines'
    type: git
    ref: 'refs/heads/Release/v4.0'

extends:
  template: pipelines/quick-build/back.yaml@Pulse
  parameters:
    deployToDev: ${{ parameters.deployToDev }}
    deployToItg: ${{ parameters.deployToItg }}
    srcPath: src/ApiGateway/ApiGateway.csproj
    domain: gtw
    name: ${{ parameters.squad }}
    appType: webApp
    squad: ${{ parameters.squad }}
    id: ${{ iif(eq(parameters.squad, 'transverse'), '02',
        iif(eq(parameters.squad, 'tokyo'), '03',
        iif(eq(parameters.squad, 'frydge'), '04',
        iif(eq(parameters.squad, 'forrest'), '05',
        iif(eq(parameters.squad, 'joker'), '06', '00'))))) }}
