name: $(TeamProject)_$(Build.DefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)

trigger: none

pool:
  vmImage: windows-latest

parameters:
- name: devIndex
  type: number
  default: 0
- name: deployType
  displayName: "Technical parameter : don t modify it !"
  type: string
  default: 'standard'

resources:
  repositories:
    - repository: CICD
      name: 'Plateforme Technologique/CICD'
      type: git
      ref: 'refs/heads/Release/v6.1'

stages:
- template: templates/update-gateway.yaml
  parameters:
    devIndex: ${{ parameters.devIndex }}
    deployType: ${{ parameters.deployType }}
