name: $(Date:yyyyMMdd)$(Rev:.r)-$(SourceBranchName)

trigger:
  - main
  - feature/*
  - bugfix/*
  - hotfix/* 

pool:
  vmImage: windows-latest

parameters:
- name: devIndex
  type: number
  default: 0
- name: deployType
  displayName: "Technical parameter : don t modify it !"
  type: string
  default: 'standard'
  values:
    - standard
    - onlyDev

resources:
  repositories:
  - repository: Pulse
    name: 'Pulse.Operations.Pipelines'
    type: git
    ref: 'refs/heads/Release/v3.0'

stages:
- template: templates/update-gateway.yaml
  parameters:
    devIndex: ${{ parameters.devIndex }}
    deployType: ${{ parameters.deployType }}
