name: $(Date:yyyyMMdd)$(Rev:.r)-$(SourceBranchName)

trigger:
  branches:
    include:
     - main
  paths:
    include:
    - src/Config

pool:
  vmImage: windows-latest

parameters:
- name: deployToDev
  displayName: 'Déployer sur DEV'
  type: boolean
  default: false
- name: deployToItg
  displayName: 'Déployer sur ITG'
  type: boolean
  default: true
- name: deployToRec
  displayName: 'Déployer sur REC'
  type: boolean
  default: true
- name: deployToPrd
  displayName: 'Déployer sur PROD'
  type: boolean
  default: true
- name: squad
  type: string
  default: none
  values:
    - none
    - transverse
    - tokyo
    - frydge
    - forrest
    - joker

stages:
- template: templates/update-gateway.yaml
  parameters:
    deployToDev: ${{ parameters.deployToDev }}
    deployToItg: ${{ parameters.deployToItg }}
    deployToRec: ${{ parameters.deployToRec }}
    deployToPrd: ${{ parameters.deployToPrd }}
    squad: ${{ parameters.squad }}